version: "3.7"

services:
  timescale:
    image: timescale/timescaledb:1.7.4-pg12
    container_name: timescale
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
#      POSTGRES_HOST: timescale
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: temp-pass
    networks:
      timescale_network:

  pgadmin:
    # Name of the container this service creates. Otherwise it's prefixed with the git repo name
    image: "dpage/pgadmin4:latest"
    container_name: pgadmin
    restart: unless-stopped
    volumes:
      # So the database server settings get saved and stored even if the container is replaced or deleted
      - /var/lib/pgadmin4
    ports:
      - 9000:9000
    environment:
      PGADMIN_LISTEN_PORT: 9000
      PGADMIN_DEFAULT_EMAIL: mrraidas@gmail.com
      PGADMIN_DEFAULT_PASSWORD: temp-pass
    networks:
      timescale_network:

networks:
  timescale_network:
    external: true